# Generated by Django 4.1.7 on 2023-02-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectCredit',
            field=models.CharField(default='', max_length=1),
        ),
    ]
