# Generated by Django 4.1.7 on 2023-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniApp', '0002_alter_subject_subjectcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectstudent', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
